version: "2.4"

services:
  drive:
    build:
      context: .
    image: lgsvl/lanefollowing:latest
    container_name: lanefollowing
    volumes:
      - ${HOME}/.Xauthority:/lgsvl/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/lanefollowing
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - LIBOVERLAY_SCROLLBAR=0
      - GTK2_RC_FILES=/usr/share/themes/Adwaita/gtk-2.0/gtkrc
      - GTK_THEME=Adwaita
      - CUDA_CACHE_PATH=/lanefollowing/.nv
    runtime: nvidia
    network_mode: host
    init: true
    privileged: true
    command: /lanefollowing/scripts/drive.sh
  
  collect:
    build:
      context: .
    image: lgsvl/lanefollowing:latest
    container_name: lanefollowing_training
    volumes:
      - ${HOME}/.Xauthority:/lgsvl/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/lanefollowing
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - LIBOVERLAY_SCROLLBAR=0
      - GTK2_RC_FILES=/usr/share/themes/Adwaita/gtk-2.0/gtkrc
      - GTK_THEME=Adwaita
      - CUDA_CACHE_PATH=/lanefollowing/.nv
    runtime: nvidia
    network_mode: host
    init: true
    privileged: true
    command: /lanefollowing/scripts/collect.sh
  
  jupyter:
    build:
      context: .
    image: lgsvl/lanefollowing:latest
    container_name: lanefollowing_jupyter
    volumes:
      - ${HOME}/.Xauthority:/lgsvl/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/lanefollowing
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - LIBOVERLAY_SCROLLBAR=0
      - GTK2_RC_FILES=/usr/share/themes/Adwaita/gtk-2.0/gtkrc
      - GTK_THEME=Adwaita
      - CUDA_CACHE_PATH=/lanefollowing/.nv
    runtime: nvidia
    network_mode: host
    init: true
    privileged: true
    tty: true
    stdin_open: true
    command: ["/run_jupyter.sh", "--allow-root", "--ip=localhost"]

