drive:
    ros__parameters:
        visualization: false
        model_path: "/lanefollowing/ros2_ws/src/lane_following/model/model.h5"
        # object_model_path: "/lanefollowing/ros2_ws/src/lane_following/model/yolov2-tiny.h5"
        object_model_path: "/lanefollowing/ros2_ws/src/lane_following/model/yolo.h5"
